package kz.aitu.taskhub.ui

import androidx.compose.runtime.staticCompositionLocalOf
import java.util.Locale

enum class Msg(val ru: String, val en: String, val kk: String) {
    HOME("Главная", "Home", "Басты бет"),
    TASKS("Задачи", "Tasks", "Тапсырмалар"),
    SCHEDULE("Расписание", "Schedule", "Сабақ кестесі"),
    SETTINGS("Настройки", "Settings", "Баптаулар"),
    REFRESH("Обновить", "Refresh", "Жаңарту"),
    ADD_TASK("Новая задача", "New task", "Жаңа тапсырма"),
    ADD_LESSON("Новая пара", "New class", "Жаңа сабақ"),
    SAVE("Сохранить", "Save", "Сақтау"),
    CANCEL("Отмена", "Cancel", "Бас тарту"),
    DELETE("Удалить", "Delete", "Жою"),
    EDIT("Редактировать", "Edit", "Өңдеу"),
    CONFIRM_DELETE("Удалить «%s»?", "Delete “%s”?", "«%s» жойылсын ба?"),
    ACTIVE("Активные", "Active", "Белсенді"),
    DONE("Готовые", "Completed", "Орындалған"),
    ALL("Все", "All", "Барлығы"),
    SEARCH("Поиск по задачам и предметам", "Search tasks and subjects", "Тапсырма немесе пәнді іздеу"),
    HIGH("Высокий", "High", "Жоғары"),
    NORMAL("Обычный", "Normal", "Қалыпты"),
    PRIORITY("Приоритет", "Priority", "Басымдық"),
    SUBJECT("Предмет", "Subject", "Пән"),
    TASK_TITLE("Что нужно сделать?", "What needs to be done?", "Не істеу керек?"),
    DEADLINE("Дедлайн", "Deadline", "Мерзім"),
    CLEAR("Убрать", "Clear", "Тазалау"),
    DATE("Дата", "Date", "Күн"),
    TIME("Время", "Time", "Уақыт"),
    NO_DEADLINE("Без срока", "No deadline", "Мерзімсіз"),
    DAY("День недели", "Weekday", "Апта күні"),
    WEEK("Вся неделя", "Whole week", "Бүкіл апта"),
    ALL_WEEKS("Каждую неделю", "Every week", "Әр апта"),
    NUMERATOR("Числитель", "Odd week", "Тақ апта"),
    DENOMINATOR("Знаменатель", "Even week", "Жұп апта"),
    START("Начало", "Start", "Басталуы"),
    END("Конец", "End", "Аяқталуы"),
    ROOM("Аудитория", "Room", "Аудитория"),
    TEACHER("Преподаватель", "Teacher", "Оқытушы"),
    TYPE("Тип занятия", "Class type", "Сабақ түрі"),
    TIMEZONE("Часовой пояс", "Time zone", "Уақыт белдеуі"),
    LANGUAGE("Язык", "Language", "Тіл"),
    REMINDERS("Напоминания о парах", "Class reminders", "Сабақ еске салғыштары"),
    REMINDER_MINUTES("За сколько минут напомнить", "Minutes before class", "Сабаққа дейінгі минут"),
    AT_START("В начале", "At start", "Басталғанда"),
    PARITY_OFFSET("Сменить чётность недель", "Swap odd/even weeks", "Тақ/жұп апталарды ауыстыру"),
    HORIZON("Горизонт дашборда, дней", "Dashboard horizon, days", "Шолу аралығы, күн"),
    ISO_WEEK("ISO-неделя %s", "ISO week %s", "ISO аптасы %s"),
    TODAY_COUNT("Пар сегодня: %s", "Classes today: %s", "Бүгінгі сабақтар: %s"),
    ACTIVE_COUNT("Активных задач: %s", "Active tasks: %s", "Белсенді тапсырмалар: %s"),
    CURRENT("Сейчас", "Now", "Қазір"),
    NEXT("Следующая пара", "Next class", "Келесі сабақ"),
    NO_CLASS("Пары нет", "No class", "Сабақ жоқ"),
    NO_NEXT("Нет пар в ближайшие 14 дней", "No classes in the next 14 days", "Келесі 14 күнде сабақ жоқ"),
    OVERDUE("Просроченные", "Overdue", "Мерзімі өткен"),
    UPCOMING("Ближайшие дедлайны", "Upcoming deadlines", "Жақын мерзімдер"),
    LATER("За горизонтом: %s", "Beyond horizon: %s", "Аралықтан тыс: %s"),
    MORE("Показать все (%s)", "Show all (%s)", "Барлығын көрсету (%s)"),
    EMPTY("Пока ничего нет", "Nothing here yet", "Әзірге ештеңе жоқ"),
    HELLO("Привет, %s", "Hello, %s", "Сәлем, %s"),
    LOGIN("Войти", "Sign in", "Кіру"),
    REGISTER("Создать аккаунт", "Create account", "Тіркелу"),
    USERNAME("Логин", "Username", "Логин"),
    PASSWORD("Пароль", "Password", "Құпиясөз"),
    REPEAT_PASSWORD("Повторите пароль", "Repeat password", "Құпиясөзді қайталаңыз"),
    NAME("Имя", "Name", "Аты"),
    LOGOUT("Выйти", "Sign out", "Шығу"),
    LOGOUT_CONFIRM("Выйти из аккаунта на этом телефоне?", "Sign out on this phone?", "Осы телефондағы аккаунттан шығу керек пе?"),
    SERVER("Адрес сервера", "Server address", "Сервер мекенжайы"),
    SERVER_HINT("Mac и телефон должны быть в одной Wi-Fi-сети. HTTP — только для локальной отладки.", "Mac and phone must use the same Wi-Fi. HTTP is for local debugging only.", "Mac пен телефон бір Wi-Fi желісінде болуы керек. HTTP тек жергілікті тексеру үшін."),
    AUTH_HINT("Собственный аккаунт TaskHub. Telegram не нужен.", "Your own TaskHub account. No Telegram needed.", "Жеке TaskHub аккаунты. Telegram қажет емес."),
    CREDENTIAL_HINT("Логин: 3–32 символа a–z, 0–9, _. Пароль: 10–128 символов.", "Username: 3–32 characters a–z, 0–9, _. Password: 10–128 characters.", "Логин: 3–32 таңба a–z, 0–9, _. Құпиясөз: 10–128 таңба."),
    INVALID_FORM("Проверь поля формы.", "Check the form fields.", "Форма өрістерін тексеріңіз."),
    PASSWORD_MISMATCH("Пароли не совпадают.", "Passwords do not match.", "Құпиясөздер сәйкес емес."),
    INVALID_TIME("Укажи время ЧЧ:ММ; конец должен быть позже начала.", "Use HH:mm; end must be after start.", "СС:ММ енгізіңіз; аяқталуы басталуынан кейін болуы керек."),
    INVALID_DATE("Проверь дату и время дедлайна.", "Check the deadline date and time.", "Мерзімнің күні мен уақытын тексеріңіз."),
    INVALID_URL("Некорректный URL. Для релизной версии нужен HTTPS.", "Invalid URL. Release builds require HTTPS.", "URL қате. Релизге HTTPS қажет."),
    NETWORK_ERROR("Не удалось связаться с сервером. Проверь адрес и подключение.", "Cannot reach the server. Check its address and your connection.", "Серверге қосылу мүмкін емес. Мекенжай мен желіні тексеріңіз."),
    SESSION_EXPIRED("Сессия истекла. Войди снова.", "Session expired. Sign in again.", "Сессия аяқталды. Қайта кіріңіз."),
    AUTH_ERROR("Неверный логин или пароль.", "Invalid username or password.", "Логин не құпиясөз қате."),
    USERNAME_TAKEN("Этот логин уже занят.", "Username already taken.", "Бұл логин бос емес."),
    RATE_LIMIT("Слишком много попыток. Подожди минуту.", "Too many attempts. Wait a minute.", "Тым көп әрекет. Бір минут күтіңіз."),
    SERVER_ERROR("Ошибка сервера (%s)", "Server error (%s)", "Сервер қатесі (%s)"),
    CACHE_NOTICE("Показаны сохранённые данные. Для изменений нужен сервер.", "Showing saved data. Changes require a server connection.", "Сақталған деректер көрсетілген. Өзгерту үшін сервер қажет."),
    RETRY("Повторить", "Retry", "Қайталау"),
    CLOSE("Закрыть", "Close", "Жабу"),
    CHANGE_PASSWORD("Изменить пароль", "Change password", "Құпиясөзді өзгерту"),
    CURRENT_PASSWORD("Текущий пароль", "Current password", "Қазіргі құпиясөз"),
    NEW_PASSWORD("Новый пароль", "New password", "Жаңа құпиясөз"),
    PASSWORD_CHANGED("Пароль изменён. Другие сессии завершены.", "Password changed. Other sessions have been signed out.", "Құпиясөз өзгертілді. Басқа сессиялар аяқталды."),
    ALLOW_NOTIFICATIONS("Разрешить уведомления Android", "Allow Android notifications", "Android хабарландыруларына рұқсат беру"),
    ALLOW_EXACT("Разрешить точные напоминания", "Allow precise reminders", "Дәл еске салғыштарға рұқсат беру"),
    NOTIFICATIONS_ON("Уведомления Android разрешены", "Android notifications enabled", "Android хабарландыруларына рұқсат берілген"),
    EXACT_ON("Точные напоминания разрешены", "Precise reminders enabled", "Дәл еске салғыштарға рұқсат берілген"),
    REMINDER_NOTE("Без разрешения на точные напоминания Android может задерживать уведомления. Сохранённые пары напоминаются и без сети; изменения подтягиваются при открытии и фоновой синхронизации.", "Without precise-alarm access Android may delay reminders. Saved classes work offline; changes sync on open and in the background.", "Дәл еске салғышқа рұқсатсыз Android хабарландыруларды кешіктіруі мүмкін. Сақталған сабақтар желісіз жұмыс істейді; өзгерістер ашқанда және фондық синхрондауда жүктеледі."),
    TIME_NOTE("Все часы — в выбранном часовом поясе. Смена зоны не меняет сохранённые часы. Горизонт включает сегодня.", "All times use your chosen zone. Changing it keeps saved wall times. The horizon includes today.", "Уақыт таңдалған белдеуде көрсетіледі. Белдеуді ауыстыру сақталған сағаттарды өзгертпейді. Аралыққа бүгін кіреді."),
    PARITY_NOTE("ISO-недели: нечётная — числитель, чётная — знаменатель. Переключатель меняет их местами.", "ISO weeks: odd = numerator, even = denominator. The switch swaps them.", "ISO апталары: тақ — алым, жұп — бөлім. Ауыстырғыш оларды алмастырады."),
    CLASS_REMINDER("Скоро пара", "Class reminder", "Сабақ еске салғышы"),
    CLASS_NOW("Пара начинается", "Class starts now", "Сабақ басталады"),
    OPTIONAL("необязательно", "optional", "міндетті емес"),
    WORKING("Сохранение…", "Saving…", "Сақталуда…"),
    MON("Пн", "Mon", "Дс"),
    TUE("Вт", "Tue", "Сс"),
    WED("Ср", "Wed", "Ср"),
    THU("Чт", "Thu", "Бс"),
    FRI("Пт", "Fri", "Жм"),
    SAT("Сб", "Sat", "Сб"),
    SUN("Вс", "Sun", "Жс");

    fun text(language: String, vararg args: Any): String {
        val value = when (language) { "en" -> en; "kk" -> kk; else -> ru }
        return if (args.isEmpty()) value else String.format(Locale.ROOT, value, *args)
    }
}

class Labels(val language: String) {
    operator fun get(key: Msg, vararg args: Any): String = key.text(language, *args)
    fun weekday(day: Int): String = get(listOf(Msg.MON, Msg.TUE, Msg.WED, Msg.THU, Msg.FRI, Msg.SAT, Msg.SUN)[day - 1])
    fun parity(value: String): String = get(when (value) { "numerator" -> Msg.NUMERATOR; "denominator" -> Msg.DENOMINATOR; else -> Msg.ALL_WEEKS })
}

val LocalLabels = staticCompositionLocalOf { Labels("ru") }
